---

language: bash
sudo: required
install:
  - sudo apt-get install zsh
  - mkdir -p ${HOME}/bin
  - curl -L https://github.com/mvdan/sh/releases/download/v3.0.0/shfmt_v3.0.0_linux_amd64 -o ${HOME}/bin/shfmt
  - chmod 755 ${HOME}/bin/shfmt
script:
  - make test
